#!/usr/bin/env bash
# -*- mode: shell-script; -*-
#
# userend/install.sh — Hermes Analytics User-Side Setup
#
# Prompts for username and optional remote server URL, writes
# ~/.hermes-analytics.conf, and makes hermes-snapshot executable.
#
# Usage:
#   ./install.sh                Interactive setup (idempotent)
#   ./install.sh --reconfigure   Force re-prompt even if config exists
set -euo pipefail

# ────────────────────────────────────────────────────────────────────────
# Helpers
# ────────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m' # No Color

info()    { echo -e "${BLUE}→${NC} $*"; }
success() { echo -e "${GREEN}✓${NC} $*"; }
warn()    { echo -e "${YELLOW}⚠${NC} $*"; }
error()   { echo -e "${RED}✗${NC} $*"; }

# ────────────────────────────────────────────────────────────────────────
# Locate paths
# ────────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="$HOME/.hermes-analytics.conf"
HERMES_SNAPSHOT="$SCRIPT_DIR/hermes-snapshot"

RECONFIGURE=false
if [[ "${1:-}" == "--reconfigure" ]]; then
    RECONFIGURE=true
fi

# ────────────────────────────────────────────────────────────────────────
# Banner
# ────────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}═══════════════════════════════════════════${NC}"
echo -e "${BOLD}  Hermes Analytics — User Setup${NC}"
echo -e "${BOLD}═══════════════════════════════════════════${NC}"
echo ""

# ────────────────────────────────────────────────────────────────────────
# Check for existing config
# ────────────────────────────────────────────────────────────────────────
if [[ -f "$CONFIG_FILE" ]] && [[ "$RECONFIGURE" != "true" ]]; then
    info "Config already exists at ${CONFIG_FILE}"
    echo ""
    # Show current settings
    # shellcheck disable=SC1090
    source "$CONFIG_FILE" 2>/dev/null || true
    echo "  Username:   ${HERMES_ANALYTICS_USER:-<not set>}"
    echo "  Remote URL: ${HERMES_ANALYTICS_REMOTE:-<not set (local only)>}"
    echo ""
    warn "Config already exists. Use --reconfigure to change settings."
    echo ""
    info "Run ${BOLD}/hermes-snapshot${NC} from your agent to collect analytics."
    exit 0
fi

# ────────────────────────────────────────────────────────────────────────
# Prompt for username
# ────────────────────────────────────────────────────────────────────────
echo ""
echo -n "Enter your username for Hermes Analytics: "
read -r USERNAME

if [[ -z "$USERNAME" ]]; then
    error "Username cannot be empty."
    exit 1
fi

# Validate: alphanumeric, hyphens, underscores only
if ! [[ "$USERNAME" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    error "Username may only contain letters, numbers, hyphens, and underscores."
    exit 1
fi

# ────────────────────────────────────────────────────────────────────────
# Prompt for remote URL (optional)
# ────────────────────────────────────────────────────────────────────────
echo ""
echo -n "Analytics server URL? [skip for local-only]: "
read -r REMOTE_URL

# ────────────────────────────────────────────────────────────────────────
# Write config file
# ────────────────────────────────────────────────────────────────────────
echo ""
info "Writing config to ${CONFIG_FILE} ..."

if [[ "$RECONFIGURE" == "true" ]] && [[ -f "$CONFIG_FILE" ]]; then
    # Back up existing config
    BACKUP="${CONFIG_FILE}.bak.$(date +%Y%m%d_%H%M%S)"
    cp "$CONFIG_FILE" "$BACKUP"
    info "Backed up previous config to ${BACKUP}"
fi

{
    echo "# Hermes Analytics — User Configuration"
    echo "# Generated by userend/install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    echo ""
    echo "HERMES_ANALYTICS_USER=${USERNAME}"
    if [[ -n "$REMOTE_URL" ]]; then
        echo "HERMES_ANALYTICS_REMOTE=${REMOTE_URL}"
    fi
} > "$CONFIG_FILE"

success "Config written."

# ────────────────────────────────────────────────────────────────────────
# Make hermes-snapshot executable
# ────────────────────────────────────────────────────────────────────────
chmod +x "$HERMES_SNAPSHOT"
success "Made ${HERMES_SNAPSHOT} executable."

# ────────────────────────────────────────────────────────────────────────
# Post-install summary
# ────────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}═══════════════════════════════════════════${NC}"
echo -e "${BOLD}  Setup Complete${NC}"
echo -e "${BOLD}═══════════════════════════════════════════${NC}"
echo ""
echo -e "  ${BOLD}Username:${NC}   ${USERNAME}"
if [[ -n "$REMOTE_URL" ]]; then
    echo -e "  ${BOLD}Server:${NC}     ${REMOTE_URL}  (remote push enabled)"
else
    echo -e "  ${BOLD}Server:${NC}     local only (snapshot saved to disk)"
fi
echo ""
echo -e "  Run ${BOLD}/hermes-snapshot${NC} from your agent to collect analytics."
echo -e "  Or run ${BOLD}python3 userend/collector.py${NC} directly."
echo ""
